import React from 'react';
import { Link } from 'react-router-dom';
import { BiHappyBeaming } from 'react-icons/bi';
import { FaRegEye, FaHandshake } from 'react-icons/fa';
import { BsCollectionPlayFill } from 'react-icons/bs';
import GlambotAdvantageItem from '../components/GlambotAdvantageItem';
import EventItem from '../components/EventItem';
import { Helmet } from 'react-helmet';

const Corporate = () => {
  return (
    <>
      <Helmet>
        <meta charSet='utf-8' />
        <title>Corporate | Aura Photobooth</title>
        <link rel='aura photobooth' href='https://auraphotobooth.ca/corporate' />
      </Helmet>
      <div className='w-screen bg-paper text-[0.9rem]'>
        {/* FIRST TOP DIV  | Corporate & Image */}
        <div className='max-w-[1420px] mx-auto bg-paper flex flex-col items-center gap-y-10'>
          <div className='flex justify-center w-screen min-h-[80vh] sm:min-h-[40vh] max-h-[60vh] relative'>
            <p className='absolute h-full w-full bg-blackTrans'></p>
            <img src='/corporate_header.png' alt='glambot image' className='w-full object-cover ' />
            <div className='absolute text-paper bottom-[14%] sm:bottom-[14%] left-[1%] sm:left-[10%] flex flex-col sm:flex-row px-5 gap-x-2 gap-y-6'>
              <div className='w-full sm:w-[60%]'>
                <h1 className='text-[2rem] tracking-wide sm:text-[2.5rem] md:text-[4rem] font-semibold'>Corporate / Charity</h1>
                <p className='w-full text-[1rem] sm:text-[1.2rem] mt-2'>We take your corporate event seriously, and we're here to support you every step of the way. We understand the importance of your mission and stand ready to elevate your event experience.</p>
              </div>
              <div className='w-full sm:w-[40%] flex items-center justify-start sm:justify-center'>
                <Link
                  to={'/contact'}
                  className='w-full sm:w-fit sm:px-12 text-center bg-secondaryLight text-nowrap brightness-[1.2] border-4 rounded-2xl tracking-wide leading-7 border-secondaryLight py-3 text-primaryLight rounded-4xl text-[0.9rem] sm:text-[1.1rem] hover:bg-blackTrans hover:text-paper transition-all duration-300 uppercase font-bold'>
                  Book Now
                </Link>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className='w-screen bg-paper text-[0.9rem] relative'>
        {/* SECOND DIV  | Details */}
        <div className='max-w-[1420px] mx-auto bg-none flex flex-col sm:flex-row items-center py-20 gap-y-10'>
          <div className='w-full flex flex-col items-start gap-y-4 px-5 text-fcPrimary leading-8 text-[1rem] tracking-wide sm:pl-10 pl-3'>
            <div className='z-20 absolute top-[-45px] sm:top-[-70px] mx-auto flex justify-start text-[3rem] select-none w-[1420px]'>
              <h3 className='bg-paper ml-[20px] sm:ml-0 px-10 py-2 sm:py-5 text-primaryLight rounded-t-2xl text-[1rem] sm:text-[1.3rem] font-semibold tracking-tight'>Benefits</h3>
            </div>
            <h2 className='mb-2 text-[1.3rem] sm:text-[2rem] font-bold text-primaryLight text-center w-full leading-[2rem] sm:leading-[3rem] sm:text-start uppercase'>Why Incorporating Photo and Video Activations into Your Event Is Essential</h2>
            <div className='flex justify-center flex-col items-start px-5 sm:px-0 gap-y-7'>
              <GlambotAdvantageItem icon={<BiHappyBeaming className='text-[3rem] w-10' />} header={`Unforgettable Brand Moments`} text={`We specialize in capturing the of your brand, transforming ordinary moments into extraordinary memories.`} />
              <GlambotAdvantageItem icon={<FaRegEye className='text-[3rem] w-10' />} header={`Maximize Your Brand's Visibility`} text={`Elevate your brand visibility and stand out from the crowd with us! Achieve this through branded backdrops, custom branding, and more.`} />
              <GlambotAdvantageItem icon={<FaHandshake className='text-[3rem] w-10' />} header={`Captivating Content Creation`} text={`Forge meaningful connections with your audience through interactive experiences.`} />
              <GlambotAdvantageItem icon={<BsCollectionPlayFill className='text-[3rem] w-10' />} header={`Unforgettable Brand Moments`} text={`Fuel your marketing efforts with captivating content generated by one of our booth.`} />
            </div>
          </div>
        </div>
      </div>
      <div className='w-screen bg-primaryLight text-[0.9rem]'>
        {/* THIRD DIV | 2 videos */}
        <div className='max-w-[1420px] mx-auto bg-none flex flex-nowrap justify-center items-center'>
          <div className='grid grid-cols-1 md:grid-cols-3 w-full gap-y-10'>
            {/* First video */}
            <div className='col-span-1'>
              <video
                autoPlay={true}
                className='z-10 w-full h-[30rem] md:h-full mx-auto md:w-full object-cover'
                loop
                muted
                playsInline
                onClick={(e) => {
                  e.preventDefault();
                }}>
                <source src='/corporate1.mp4' type='video/mp4' />
              </video>
            </div>
            {/* Text */}
            <div className='w-full col-span-1 flex flex-col items-center justify-center gap-y-5 px-5 sm:px-7 text-paper leading-[3.5rem] text-[2rem] sm:text-[2.4rem] tracking-wide'>
              <h4 className='text-center'>Step into the spotlight and let your brand's unique aura shine with our booths </h4>
              <Link to={'/contact'} className='group mt-10 text-[1rem] text-secondaryLight font-semibold text-nowrap hover:brightness-150 transition-all duration-300 relative overflow-hidden'>
                Contact us {`>`}
                <span className='w-full bg-none border-b-secondaryLight border-b-[2px] absolute left-[-120px] group-hover:left-0 bottom-3 transition-all duration-300'></span>
              </Link>
            </div>
            {/* Second Video */}
            <div className='col-span-1'>
              <video
                autoPlay={true}
                className='z-10 w-full h-[40rem] md:h-full mx-auto md:w-full object-cover'
                loop
                muted
                playsInline
                onClick={(e) => {
                  e.preventDefault();
                }}>
                <source src='/corporate2.mp4' type='video/mp4' />
              </video>
            </div>
          </div>
        </div>
      </div>
      <div className='w-screen bg-secondaryLight text-[0.9rem] relative'>
        {/* THIRD DIV | 2 videos */}
        <div className='max-w-[1420px] mx-auto bg-none flex flex-col flex-nowrap justify-center items-center py-10'>
          <h2 className='mb-2 text-[1.3rem] sm:text-[2rem] font-bold text-primaryLight w-full leading-[2rem] sm:leading-[3rem] uppercase py-5 text-center'></h2>
          <div className='grid grid-cols-1 md:grid-cols-2 w-full gap-y-10 gap-x-10 px-10'>
            <div className='z-20 absolute top-[-39px] sm:top-[-70px] mx-auto flex justify-start text-[3rem] select-none w-[1420px]'>
              <h3 className='bg-secondaryLight px-10 py-2 sm:py-5 text-primaryLight rounded-t-2xl text-[1rem] sm:text-[1.3rem] font-semibold tracking-tight'>Booths</h3>
            </div>
            <EventItem
              header={'Glambot'}
              text={`Explore our professional Glambot experiences.`}
              imgElement={<img src='/glambot_1.png' alt='glambot image' className='max-h-[10rem] sm:max-h-[25rem]' />}
              learn={
                <Link to={'/glambot'} className='underline text-primaryLight font-semibold text-nowrap hover:brightness-150 transition-all duration-300'>
                  learn more
                </Link>
              }
            />
            <EventItem
              header={'360 Booth'}
              text={`Explore our professional 360 booth experiences.`}
              imgElement={<img src='/booth_1.png' alt='booth image' className='max-h-[10rem] sm:max-h-[25rem]' />}
              learn={
                <Link to={'/'} className='underline text-primaryLight font-semibold text-nowrap hover:brightness-150 transition-all duration-300'>
                  learn more
                </Link>
              }
            />
          </div>
        </div>
      </div>
    </>
  );
};

export default Corporate;
